name: Set up Go
description: 'Sets up Go and downloads verified modules'
inputs:
  stainless-api-key:
    required: false
    description: Credential for the SDK staging repository
  go-version:
    required: false
    description: Go version or version range
  cache-dependency-path:
    required: false
    description: Dependency files used for caching
runs:
  using: composite
  steps:
    - uses: stainless-api/retrieve-github-access-token@2f0857da7cbda281fff76af3def0681f915fb796 # v1.0.1
      id: get_token
      if: github.repository == 'stainless-sdks/x-twitter-scraper-terraform'
      with:
        repo: stainless-sdks/x-twitter-scraper-go
        stainless-api-key: ${{ inputs.stainless-api-key }}

    - name: Configure Git for the SDK staging repository
      if: github.repository == 'stainless-sdks/x-twitter-scraper-terraform'
      shell: bash
      env:
        STAINLESS_GITHUB_ACCESS_TOKEN: ${{ steps.get_token.outputs.github_access_token }}
      run: git config --global url."https://x-access-token:${STAINLESS_GITHUB_ACCESS_TOKEN}@github.com/stainless-sdks/x-twitter-scraper-go".insteadOf "https://github.com/stainless-sdks/x-twitter-scraper-go"

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ./go.mod
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Download verified modules
      shell: bash
      run: ./scripts/bootstrap
