#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Running formatters"
gofmt -s -w .

echo "==> Generate terraform docs"
./scripts/generate-docs
