#!/usr/bin/env bash

set -e

cd -- "$(dirname -- "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/Xquik-dev/x-twitter-scraper-go,github.com/stainless-sdks/x-twitter-scraper-go"

echo "==> Generating Terraform provider documentation"

case "$OSTYPE" in
linux*)
  export -- TMPDIR=/var/tmp
  ;;
*) ;;
esac

go mod tidy -e
exec -- go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@v0.25.0 \
  generate \
  -rendered-provider-name "X Twitter Scraper" \
  -provider-name="x-twitter-scraper"
