#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

cd -- "$(dirname -- "$0")/.."

# Mark the generated staging module as private.
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-sdks/x-twitter-scraper-go"

echo "==> Generating Terraform provider documentation"

case "$OSTYPE" in
linux*)
  export -- TMPDIR=/var/tmp
  ;;
*) ;;
esac

go mod download
go mod verify
exec -- go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@v0.25.0 \
  generate \
  -rendered-provider-name "X Twitter Scraper" \
  -provider-name="x-twitter-scraper"
