name: CI
on:
  push:
    branches:
      - '**'
      - '!integrated/**'
      - '!stl-preview-head/**'
      - '!stl-preview-base/**'
      - '!generated'
      - '!codegen/**'
      - 'codegen/stl/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

env:
  GOPRIVATE: github.com/Xquik-dev/x-twitter-scraper-go,github.com/stainless-sdks/x-twitter-scraper-go

permissions:
  # Read repository source for checkout and local actions.
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ${{ startsWith(github.repository, 'stainless-sdks/') && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Link staging branch
        if: github.repository == 'stainless-sdks/x-twitter-scraper-terraform'
        env:
          STAINLESS_REF_NAME: ${{ github.ref_name }}
        run: |
          ./scripts/link "github.com/stainless-sdks/x-twitter-scraper-go@${STAINLESS_REF_NAME}" || true

      - name: Run lints
        run: ./scripts/lint

  test:
    name: Test
    runs-on: ${{ startsWith(github.repository, 'stainless-sdks/') && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Link staging branch
        if: github.repository == 'stainless-sdks/x-twitter-scraper-terraform'
        env:
          STAINLESS_REF_NAME: ${{ github.ref_name }}
        run: |
          ./scripts/link "github.com/stainless-sdks/x-twitter-scraper-go@${STAINLESS_REF_NAME}" || true

      - name: Run tests
        run: ./scripts/test
